version: '3'
services:
  # Your app here, specify CONTAINER in env: below to be your containers: opp1 appServer appProxy

  restarter:
    image: dockercron
    build:
      # if you git clone https://github.com/rgon/dockercron
      # set context: ./dockercron
      context: ./
      dockerfile: Dockerfile
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    environment:
      - CRONFREQ=30 06 * * *
      - CONTAINER=spotifyd
    restart: unless-stopped
